---
title: "raw discret data - group discrete curves"
output: html_document
date: "2025-11-21"
---





```{r plots raw data}

rmarkdown::render("01a_data_preparation.Rmd", envir = globalenv(), quiet = TRUE)


plot_raw_curves <- function(all_groups, Time, title_gp, col,
                            ylim_global = NULL) {
  
  mat <- as.matrix(all_groups)
  
  plot(
  Time, mat[, 1],
  type = "p", pch = 16, cex = 0.9,
  col = col,
  main = title_gp,
  xlab = "Time (sec)",
  ylab = "fEPSP % of baseline",
  ylim = ylim_global
)

  
  if (ncol(mat) > 1) {
    for (i in 2:ncol(mat)) {
      points(Time, mat[, i], col = col, pch = 16, cex = 0.9)
    }
  }
}


if (!dir.exists("figures_raw_curves")) dir.create("figures_raw_curves")

ylim_global <- range(unlist(all_groups), na.rm = TRUE)

for (i in seq_along(all_groups)) {
  
  png(filename = paste0("figures_raw_curves/", groups_names[i], ".png"),
    width = 1200, height = 800, res = 150
  )
  
  plot_raw_curves(
    all_groups = all_groups[[i]],
    Time = Time,
    title_gp = groups_names[i],
    col = colors[i],
    ylim_global = ylim_global
  )
  
  #abline(h = 150, col = "black", lwd = 2, lty = 2)
  grid()
  
  dev.off()
}


```





```{r plots mean and var}

#Function to compute mean & SEM (raw data)

compute_mean_sem_raw <- function(mat) {
  mean_curve <- apply(mat, 1, mean, na.rm = TRUE)
  
  sem_curve <- apply(mat, 1, function(x) {
    sd(x, na.rm = TRUE) / sqrt(sum(!is.na(x)))
  })
  
  list(mean = mean_curve, sem = sem_curve)
}


# Compute global Y-limits for all groups (same scale)

grid <- Time  # X-axis vector

all_vals <- unlist(
  lapply(all_groups, function(mat) {
    stats <- compute_mean_sem_raw(mat)
    c(stats$mean - stats$sem, stats$mean + stats$sem)
  })
)

ylim_global <- range(all_vals)


# Plot mean ± SEM for all groups

if(!dir.exists("figures_raw_data")) dir.create("figures_raw_data")

for (i in seq_along(all_groups)) {
  
  stats <- compute_mean_sem_raw(all_groups[[i]])
  
  mean_curve <- stats$mean
  sem_curve  <- stats$sem
  
  # output file name 
  file_name <- paste0("figures_raw_data/", groups_names[i], ".png")
  
  
  png(filename = file_name, width = 1200, height = 800, res = 150)

  # Colors
  point_col   <- "black"                         # points always black
  whisker_col <- adjustcolor(colors[i], 0.9)     # whiskers in group color
  
  # Plot mean points only (no lines)
  plot(grid, mean_curve,
       type="p", pch=16, cex=0.9,
       col=point_col,
       ylim = ylim_global,
       xlab = "Time (sec)",
       ylab = "fEPSP (% baseline)",
       main = groups_names[i])
  
  # Compute cap width automatically (small horizontal whisker caps)
  cap_width <- diff(range(grid)) / 200
  
  # ---- SEM whiskers (vertical) ----
  segments(grid,
           mean_curve - sem_curve,
           grid,
           mean_curve + sem_curve,
           col = whisker_col,
           lwd = 2)
  
  # ---- SEM whisker caps ----
  segments(grid - cap_width,
           mean_curve - sem_curve,
           grid + cap_width,
           mean_curve - sem_curve,
           col = whisker_col,
           lwd = 2)
  
  segments(grid - cap_width,
           mean_curve + sem_curve,
           grid + cap_width,
           mean_curve + sem_curve,
           col = whisker_col,
           lwd = 2)
  
  # Reference line at 150%
  abline(h = 150, col = "black", lty = 2, lwd = 2)
  
  # Background grid
  grid()
  
  dev.off()

}
```






```{r anova and boxplot}


library(dplyr)
library(ggplot2)
library(ggpubr)
library(effectsize)


groups_names <- names(all_groups)

metadata <- data.frame(
  animal   = character(),
  genotype = character(),
  sex      = character(),
  age      = character(),
  stringsAsFactors = FALSE
)

for (name in groups_names) {
  
  mat <- all_groups[[name]]
  n_animals <- ncol(mat)
  
  genotype <- ifelse(grepl("WT", name), "WT", "HRM")
  
  sex <- ifelse(grepl("^males", name), "Male",
                ifelse(grepl("^females", name), "Female", NA))
  age      <- ifelse(grepl("juv", name), "Juvenile",
                     ifelse(grepl("ado", name), "Adolescent",
                            ifelse(grepl("adu", name), "Adult", "Age")))
  
  temp <- data.frame(
    animal   = paste0(name, "_", seq_len(n_animals)),
    genotype = genotype,
    sex      = sex,
    age      = age,
    stringsAsFactors = FALSE
  )
  
  metadata <- bind_rows(metadata, temp)
}


Time <- seq(
  from = 0,
  to   = 2400,                        
  length.out = nrow(all_groups[[1]])
)


# 3. Compute mean fEPSP over last 10–15 minutes (per animal)

last10_idx <- which(Time >= max(Time) - 925)  # ~15 min

mean_values <- numeric()

for (i in seq_along(all_groups)) {
  mat <- all_groups[[i]]
  means <- colMeans(mat[last10_idx, , drop = FALSE], na.rm = TRUE)
  mean_values <- c(mean_values, means)
}


# 4. Combine metadata + mean values


individual_means <- metadata
individual_means$mean_value <- mean_values


individual_means <- individual_means %>%
  mutate(
    genotype = factor(genotype, levels = c("WT", "HRM")),
    sex      = factor(sex, levels = c("Male", "Female")),
    age      = factor(age, levels = c("Juvenile", "Adolescent", "Adult", "Age"))
  ) %>%
  droplevels()


# 5. Sanity checks 


print(table(individual_means$genotype))
print(table(individual_means$sex))
print(table(individual_means$age))


# 6. Three-way ANOVA (biological unit = animal)

anova_result <- aov(
  mean_value ~ genotype + sex + age + sex * genotype + sex * age + age * genotype + sex * age * genotype,
  data = individual_means
)

eta_squared(anova_result, partial = TRUE)
summary(anova_result)



# Optional post-hoc
TukeyHSD(anova_result)

ggboxplot(
  individual_means,
  x = "genotype",
  y = "mean_value",
  color = "sex",
  palette = c("#0072B2", "#D55E00"),
  add = "jitter"
) +
  facet_wrap(~ age) +
  labs(
    x = "Genotype",
    y = "Mean fEPSP (% baseline, last 10–15 min)",
    title = "LTP magnitude per animal"
  ) +
  theme_classic(base_size = 14)



```


