---
title: "Smoothed Functional Data — Group Curves"
output: html_document
date: "2025-11-21"
---

```{r plots fd data}

rmarkdown::render("01a_data_preparation.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("01b_data_preparation.Rmd", envir = globalenv(), quiet = TRUE)


#-------------------------Plot group's curves------------------------


grid <- seq(min(Time), max(Time), length.out = 200)

all_vals <- unlist(lapply(all_fd_groups, function(fd) eval.fd(grid, fd)))
ylim_global <- range(all_vals)
ylim_global


plot_gp_curves <- function(fd_gp, title_gp, col, lty,
                         ylim_global = NULL) {
  
  
  grid <- seq(min(Time), max(Time), length.out = 200)
  mat  <- eval.fd(grid, fd_gp)    
  
  #first curves
  plot(grid, mat[, 1],type='l', col = col,lty=lty, lwd = 2,
       main = title_gp, xlab = "Time (sec)", ylab = "fESPS % of baseline",
       ylim = ylim_global)
  
  #adding the other curves of the group
  if (ncol(mat) > 1) {
    for (i in 2:ncol(mat)) {
      lines(grid, mat[, i],lty= lty, col = col, lwd = 2)
    }
  }
}

if (!dir.exists("figures_smooth_data")) dir.create("figures_smooth_data")

for (i in 1:length(all_fd_groups)) {
  
  file_name <- paste0("figures_smooth_data/", groups_names[i], ".png")
  
  png(filename = file_name, width = 1200, height = 800, res = 150)
  
  plot_gp_curves(
    fd_gp = all_fd_groups[[i]],
    title_gp = groups_names[i],
    col = colors[i],
    lty =lty[i],
    ylim_global = ylim_global
    
    
  )
  abline(h = 150, col = "black", lwd = 2, lty = 2)
  grid()
  
  dev.off()
}

```




```{r functional box genotype sex}

male_WT_groups  <- grep("^Males WT",  names(all_fd_groups), value = TRUE)
male_HRM_groups <- grep("^Males HRM", names(all_fd_groups), value = TRUE)

female_WT_groups  <- grep("^Females WT",  names(all_fd_groups), value = TRUE)
female_HRM_groups <- grep("^Females HRM", names(all_fd_groups), value = TRUE)


male_WT_mat  <- do.call(cbind, lapply(all_fd_groups[male_WT_groups],  function(fd) eval.fd(grid, fd)))
male_HRM_mat <- do.call(cbind, lapply(all_fd_groups[male_HRM_groups], function(fd) eval.fd(grid, fd)))

female_WT_mat  <- do.call(cbind, lapply(all_fd_groups[female_WT_groups],  function(fd) eval.fd(grid, fd)))
female_HRM_mat <- do.call(cbind, lapply(all_fd_groups[female_HRM_groups], function(fd) eval.fd(grid, fd)))

dir.create("figures_fboxplot_genotypes_sex", showWarnings = FALSE)

# MALES WT
png("figures_fboxplot_genotypes_sex/fbplot_males_WT.png", width=1400, height=900, res=150)
plot_fb(male_WT_mat, grid, "Functional Boxplot – Males WT", ylim_global)
dev.off()

# MALES HRM
png("figures_fboxplot_genotypes_sex/fbplot_males_HRM.png", width=1400, height=900, res=150)
plot_fb(male_HRM_mat, grid, "Functional Boxplot – Males HRM", ylim_global)
dev.off()

# FEMALES WT
png("figures_fboxplot_genotypes_sex/fbplot_females_WT.png", width=1400, height=900, res=150)
plot_fb(female_WT_mat, grid, "Functional Boxplot – Females WT", ylim_global)
dev.off()

# FEMALES HRM
png("figures_fboxplot_genotypes_sex/fbplot_females_HRM.png", width=1400, height=900, res=150)
plot_fb(female_HRM_mat, grid, "Functional Boxplot – Females HRM", ylim_global)
dev.off()

```




