---
title: "plots velocity and acceleration"
output: html_document
date: "2025-11-21"
---


```{r}

rmarkdown::render("04_mean_and_variance_functions.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("05_kinetics_derivatives.Rmd", envir = globalenv(), quiet = TRUE)

legends <- groups_names

ymin <- min(sapply(all_1st_derivs, min))
ymax <- max(sapply(all_1st_derivs, max))

```



```{r velocity }

if (!dir.exists("figures_1st_derivatives")) dir.create("figures_1st_derivatives")

for (i in seq_along(fd_groups)) {
  
  file_name <- paste0("figures_1st_derivatives/1st_derivative_", legends[i], ".png")
  png(file_name, width = 1400, height = 900, res = 150)
  
  
  plot(
    Time, all_1st_derivs[[i]], type = "l", col = colors[i], lwd = 3, lty = lty[i],
    xlab = "Time (sec)", ylab = "(fEPSP % baseline)'",
    main = paste("First Derivative -", legends[i]),
    ylim = c(ymin, ymax)   # <-- same scale
  )
  
  
  abline(h = 0, col = "red", lty = 1)
  grid()
  
  dev.off()
}




```




```{r}

if (!dir.exists("matrices_cor")) dir.create("matrices_cor")

groups_list <- list(
  "females WT" = grep("^Females WT", names(fd_groups), value = TRUE),
  "males WT"   = grep("^Males WT", names(fd_groups), value = TRUE)
)

for (grp_name in names(groups_list)) {
  group_fds <- fd_groups[groups_list[[grp_name]]]
  basis_fd <- group_fds[[1]]$basis
  
  coeff_list <- lapply(group_fds, function(fd) fd$coefs)
  coeff_mat <- do.call(cbind, coeff_list)
  
  group_fd <- fd(coef = coeff_mat, basisobj = basis_fd)
  deriv_gp <- deriv.fd(group_fd)
  
  cov_fd <- var.fd(deriv_gp)
  grid <- seq(basis_fd$rangeval[1], basis_fd$rangeval[2], length.out = 500)
  
  cov_matrix <- eval.bifd(grid, grid, cov_fd)

  # --- functional correlation ---
  v <- diag(cov_matrix)
  v[v == 0] <- 1e-10
  corr_matrix <- cov_matrix / sqrt( outer(v, v) )
  
  
  png(filename = paste0("matrices_cor/corr_heatmap_", grp_name, ".png"),
    width = 1200, height = 1000, res = 150)

  
  layout(matrix(c(1,2), ncol = 2), widths = c(4,1))

  par(mar = c(5,5,4,1))
  image(grid, grid, corr_matrix,
      col = topo.colors(50),
      zlim = c(-1, 1),
      xlab = "Time (s)", ylab = "Time (s)",
      main = paste("Functional correlation -", grp_name))

  
  par(mar = c(5,2,4,4))  # marges pour la légende
  image(1, seq(-1, 1, length.out = 50), 
      matrix(seq(-1, 1, length.out = 50), nrow = 1),
      col = topo.colors(50),
      axes = FALSE,
      xlab = "", ylab = "")
  axis(4, at = seq(-1, 1, by = 0.5), las = 1)  # axe y à droite

  dev.off()

}

```




```{r}

library(fields)
zoom_start <- 1741
zoom_end   <- 2400

# zoom index zone
zoom_idx <- which(Time >= zoom_start & Time <= zoom_end)

# Y-limits for zoom zone
global_zoom_ymin <- min(sapply(all_1st_derivs, function(x) min(x[zoom_idx], na.rm = TRUE)))
global_zoom_ymax <- max(sapply(all_1st_derivs, function(x) max(x[zoom_idx], na.rm = TRUE)))


for (i in seq_along(fd_groups)) {
  
  file_name <- paste0("figures_1st_derivatives/1st_derivative_with_zoom_", legends[i], ".png")
  png(file_name, width = 1600, height = 900, res = 150)
  
  par(mfrow = c(1, 2))
  
  #### --- 1) FULL GRAPH  ---
  plot(
    Time, all_1st_derivs[[i]], type = "l",
    col = colors[i], lwd = 3, lty = lty[i],
    ylim = c(ymin, ymax),   # <-- same scale for full signal
    xlab = "Time (sec)", ylab = "Derivative",
    main = paste("Full signal -", legends[i])
  )
  abline(h = 0, col = "red")
  grid()
  
  #### --- 2) ZOOM GRAPH  ---
  plot(
    Time[zoom_idx], all_1st_derivs[[i]][zoom_idx], type = "l",
    col = colors[i], lwd = 3, lty = lty[i],
    ylim = c(global_zoom_ymin, global_zoom_ymax),   # <-- same scale for the zoom ones
    xlab = "Time (sec)", ylab = "",
    main = paste("Zoom", zoom_start, "-", zoom_end, "sec")
  )
  abline(h = 0, col = "red")
  grid()
  
  dev.off()
}



```




















```{r acceleration }

if (!dir.exists("figures_2nd_derivatives")) dir.create("figures_2nd_derivatives")

for (i in seq_along(fd_groups)) {
  
  file_name <- paste0("figures_2nd_derivatives/2nd_derivative_", legends[i], ".png")
  png(file_name, width = 1400, height = 900, res = 150)
  
  plot(
    Time, all_2nd_derivs[[i]], type = "l", col = colors[i], lwd = 3, lty = lty[i],
    xlab = "Time (sec)", ylab = "(fEPSP % baseline)'' ",
    main = paste("Second Derivative -", legends[i]),
    ylim = c(ymin, ymax)   # <-- same scale
  )
  
  abline(h = 0, col = "red", lty = 2)
  grid()
  
  dev.off()
}

```



















```{r phase_portrait_f'_vs_f''}


if (!dir.exists("figures_phase_portraits")) dir.create("figures_phase_portraits")

for (i in seq_along(fd_groups)) {

  file_name <- paste0("figures_phase_portraits/phase_fprime_vs_fdoubleprime_", legends[i], ".png")
  png(file_name, width = 1400, height = 900, res = 150)

  dx  <- all_1st_derivs[[i]]   # velocity
  ddx <- all_2nd_derivs[[i]]   # acceleration

  plot(
    dx, ddx, type = "l", lwd = 3, col = colors[i],
    xlab = "Velocity (1st derivative)",
    ylab = "Acceleration (2nd derivative)",
    main = paste("Phase Portrait: f'(t) vs f''(t) -", legends[i])
  )

  abline(h = 0, v = 0, col = "red", lty = 2)
  grid()
  dev.off()
}

```





