---
title: "apply fanova"
output: html_document
date: "2025-11-24"
---

```{r apply fanova}

rmarkdown::render("01a_data_preparation.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("01b_data_preparation.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("02_local_outlier_handling.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("04_mean_and_variance_functions.Rmd", envir = globalenv(), quiet = TRUE)
rmarkdown::render("07_functional_anova.Rmd", envir = globalenv(), quiet = TRUE)

set.seed(1234)


# Suppose having n functional observations (each in fd_groups[[i]]).  we define:

Genotype <- c("WT","HRM","WT","HRM", 
              "WT","HRM","WT","HRM",
              "WT","HRM","WT","HRM",
              "WT","HRM","WT","HRM")

Age  <- c("juv","juv","juv","juv",
          "ado","ado","ado","ado", 
          "adu", "adu","adu", "adu",
          "age", "age","age", "age")

Sex <- c("M","M","F","F",
          "M","M","F","F",
          "M","M","F","F",
          "M","M","F","F")

# Run 3-way functional ANOVA
res3 <- fanova3_FP(fd_groups, Genotype, Age, Sex, P = 2000)

# Extract
fstats <- res3$stat
dfs    <- res3$df
eta2   <- res3$effect_size_eta

# Choose which p-values to report:
#pvals <- res3$pvalue_unadj # (if we want unadjusted)
pvals <- res3$pvalue_maxT    # <-- recommended
#pvals <- res3$pvalue_BH    # (if we want FDR)
#p_value <- res3$pvalue_holm #


anova_table3 <- data.frame(
  Factor      = c("Genotype","Age","Sex","Genotype:Age","Genotype:Sex","Age:Sex","Genotype:Age:Sex"),
  F_stat      = c(fstats["FG"], fstats["FA"], fstats["FS"],
                  fstats["FAG"], fstats["FGS"], fstats["FAS"],
                  fstats["FGAS"]),
  p_value     = c(pvals["FG"],  pvals["FA"],  pvals["FS"],
                  pvals["FAG"], pvals["FGS"], pvals["FAS"],
                  pvals["FGAS"]),
  df_numer    = c(dfs["dfG"],   dfs["dfA"],   dfs["dfS"],
                  dfs["dfAG"],  dfs["dfGS"],  dfs["dfAS"],
                  dfs["dfGAS"]),
  eta2_effect = c(eta2["eta2_G"], eta2["eta2_A"], eta2["eta2_S"],
                  eta2["eta2_AG"], eta2["eta2_GS"], eta2["eta2_AS"],
                  eta2["eta2_GAS"])
)

print(anova_table3)


library(gridExtra)
library(grid)

if (!dir.exists("summary_stat_Fanova")) dir.create("summary_stat_Fanova")

png("summary_stat_Fanova/anova_table3.png", width = 1000, height = 800, res = 150)
grid.newpage()
grid.table(anova_table3, rows = NULL)
dev.off()





```



```{r algorthmic stability}



###############################################
## FUNCTIONAL ANOVA ALGORITHMIC STABILITY (LOO)
###############################################

library(dplyr)

fanova3_stability <- function(fd_groups, Genotype, Age, Sex, P = 2000) {
  n <- length(fd_groups)

  # Fit FANOVA on full dataset
  full_res <- fanova3_FP(fd_groups, Genotype, Age, Sex, P = P)
  full_F   <- full_res$stat
  full_p   <- full_res$pvalue_maxT

  # initialize lists
  loo_F_list <- vector("list", n)
  loo_p_list <- vector("list", n)

  for (i in 1:n) {
    cat("Running LOO ", i, "/", n, "\n")

    # Remove subject i
    fd_loo  <- fd_groups[-i]
    G_loo   <- Genotype[-i]
    A_loo   <- Age[-i]
    S_loo   <- Sex[-i]

    # Run FANOVA on n-1 sample
    res_loo <- fanova3_FP(fd_loo, G_loo, A_loo, S_loo, P = P)

    loo_F_list[[i]] <- res_loo$stat
    loo_p_list[[i]] <- res_loo$pvalue_maxT
  }

  # Convert to data frame for analysis
  factors <- c("FG", "FA", "FS", "FAG", "FGS", "FAS", "FGAS")

  loo_F_df <- do.call(rbind, lapply(loo_F_list, function(x) unlist(x[factors])))
  colnames(loo_F_df) <- factors

  loo_p_df <- do.call(rbind, lapply(loo_p_list, function(x) unlist(x[paste0("pvalue_", factors)])))
  colnames(loo_p_df) <- factors

  ###############################
  # Stability Metrics
  ###############################

  stability <- data.frame(
    Factor = c("Genotype","Age","Sex","Genotype:Age","Genotype:Sex","Age:Sex","Genotype:Age:Sex"),

    Full_F = unlist(full_F[factors]),
    Mean_LOO_F = apply(loo_F_df, 2, mean),
    SD_LOO_F   = apply(loo_F_df, 2, sd),
    Max_Change = apply(abs(loo_F_df - matrix(rep(unlist(full_F[factors]), n),
                                             nrow = n, byrow = TRUE)), 
                       2, max),

    Mean_Abs_Change = apply(abs(loo_F_df - matrix(rep(unlist(full_F[factors]), n),
                                                  nrow = n, byrow = TRUE)), 
                            2, mean)
  )

  return(list(
    full_model = full_res,
    loo_F = loo_F_df,
    loo_p = loo_p_df,
    stability = stability
  ))
}


set.seed(1234)
stab3 <- fanova3_stability(fd_groups, Genotype, Age, Sex, P = 2000)

stab3$stability



library(ggplot2)
library(reshape2)

looF_long <- melt(stab3$loo_F)
colnames(looF_long) <- c("LOO_index", "Factor", "F_value")

ggplot(looF_long, aes(LOO_index, F_value)) +
  geom_line() +
  geom_hline(data = data.frame(Factor = names(stab3$full_model$stat),
                               Full_F = stab3$full_model$stat),
             aes(yintercept = Full_F), color = "red", linetype = "dashed") +
  facet_wrap(~ Factor, scales = "free_y") +
  theme_bw() +
  labs(title = "LOO Algorithmic Stability for 3-way FANOVA",
       y = "F-statistic", x = "Left-out observation")


```





























































```{r Fanova three phases}

#-------------------------------------------------------------------------------
# Helper function: evaluate fd objects on a given time grid
#-------------------------------------------------------------------------------
fd_phase_eval <- function(fd_list, Time_grid) {
  lapply(fd_list, function(fd) {
    range_fd <- fd$basis$rangeval
    Time_grid <- Time_grid[Time_grid >= range_fd[1] & Time_grid <= range_fd[2]]
    eval.fd(Time_grid, fd)
  })
}

#-------------------------------------------------------------------------------
# Define time phases 
#-------------------------------------------------------------------------------
define_time_phases <- function(fd_example, n_points_per_phase = 100) {
  range_fd <- fd_example$basis$rangeval
  total_length <- diff(range_fd)
  Time_phases <- list(
    Phase1 = seq(range_fd[1], range_fd[1] + total_length/3, length.out = n_points_per_phase),
    Phase2 = seq(range_fd[1] + total_length/3, range_fd[1] + 2*total_length/3, length.out = n_points_per_phase),
    Phase3 = seq(range_fd[1] + 2*total_length/3, range_fd[2], length.out = n_points_per_phase)
  )
  return(Time_phases)
}

#-------------------------------------------------------------------------------
# Run 3-way functional ANOVA on each phase
#-------------------------------------------------------------------------------
run_anova_phases <- function(fd_list, Genotype, Age, Sex, P = 2000) {
  
  Time_phases <- define_time_phases(fd_list[[1]])
  
  results <- list()
  
  for (phase_name in names(Time_phases)) {
    cat("===== ANOVA 3-way for", phase_name, "=====\n")
    grid <- Time_phases[[phase_name]]
    
    fd_phase_vals <- fd_phase_eval(fd_list, grid)
    
    res3 <- fanova3_FP(fd_list, Genotype, Age, Sex, P = P)
    
    fstats <- res3$stat
    dfs    <- res3$df
    eta2   <- res3$effect_size_eta
    pvals  <- res3$pvalue_maxT
    
    anova_table3 <- data.frame(
      Factor      = c("Genotype","Age","Sex","Genotype:Age","Genotype:Sex","Age:Sex","Genotype:Age:Sex"),
      F_stat      = c(fstats["FG"], fstats["FA"], fstats["FS"],
                      fstats["FAG"], fstats["FGS"], fstats["FAS"],
                      fstats["FGAS"]),
      p_value     = c(pvals["FG"],  pvals["FA"],  pvals["FS"],
                      pvals["FAG"], pvals["FGS"], pvals["FAS"],
                      pvals["FGAS"]),
      df_numer    = c(dfs["dfG"],   dfs["dfA"],   dfs["dfS"],
                      dfs["dfAG"],  dfs["dfGS"],  dfs["dfAS"],
                      dfs["dfGAS"]),
      eta2_effect = c(eta2["eta2_G"], eta2["eta2_A"], eta2["eta2_S"],
                      eta2["eta2_AG"], eta2["eta2_GS"], eta2["eta2_AS"],
                      eta2["eta2_GAS"])
    )
    
    print(anova_table3)
    
    
    if (!dir.exists("summary_stat_Fanova")) dir.create("summary_stat_Fanova")
    png(paste0("summary_stat_Fanova/anova_table3_", phase_name, ".png"), 
        width = 1000, height = 800, res = 150)
    grid.newpage()
    grid.table(anova_table3, rows = NULL)
    dev.off()
    
    results[[phase_name]] <- list(
      anova_table = anova_table3,
      raw_results = res3
    )
  }
  
  return(results)
}

#-------------------------------------------------------------------------------
# Example of running ANOVA on 3 phases
#-------------------------------------------------------------------------------
set.seed(1234)

# Define factors
Genotype <- c("WT","HRM","WT","HRM", 
              "WT","HRM","WT","HRM",
              "WT","HRM","WT","HRM",
              "WT","HRM","WT","HRM")

Age  <- c("juv","juv","juv","juv",
          "ado","ado","ado","ado", 
          "adu", "adu","adu", "adu",
          "age", "age","age", "age")

Sex <- c("M","M","F","F",
         "M","M","F","F",
         "M","M","F","F",
         "M","M","F","F")

# Run ANOVA on all phases
anova_results <- run_anova_phases(fd_groups, Genotype, Age, Sex, P = 2000)

```











